//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessor.WebForms.Controls
{
    public partial class DocumentUploader
    {
        /// <summary>
        /// FileTypeSummaryText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal FileTypeSummaryText;

        /// <summary>
        /// MaxFileSizeText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal MaxFileSizeText;

        /// <summary>
        /// FilePicker control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload FilePicker;

        /// <summary>
        /// UploadButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button UploadButton;

        /// <summary>
        /// NoticeRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater NoticeRepeater;
    }
}
