//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessor.WebForms.Controls
{
    public partial class DocumentList
    {
        /// <summary>
        /// CountText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal CountText;

        /// <summary>
        /// RefreshButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton RefreshButton;

        /// <summary>
        /// EmptyState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder EmptyState;

        /// <summary>
        /// DocumentRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater DocumentRepeater;
    }
}
