//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessor.WebForms
{
    public partial class _Default
    {
        /// <summary>
        /// Uploader control.
        /// </summary>
        protected global::DocumentProcessor.WebForms.Controls.DocumentUploader Uploader;

        /// <summary>
        /// ListPanel control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel ListPanel;

        /// <summary>
        /// Documents control.
        /// </summary>
        protected global::DocumentProcessor.WebForms.Controls.DocumentList Documents;

        /// <summary>
        /// SummaryModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel SummaryModal;

        /// <summary>
        /// SummaryModalTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal SummaryModalTitle;

        /// <summary>
        /// SummaryModalDismiss control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton SummaryModalDismiss;

        /// <summary>
        /// SummaryModalBody control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal SummaryModalBody;

        /// <summary>
        /// SummaryModalClose control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton SummaryModalClose;

        /// <summary>
        /// DeleteModal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel DeleteModal;

        /// <summary>
        /// DeleteModalDismiss control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton DeleteModalDismiss;

        /// <summary>
        /// DeleteModalFileName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal DeleteModalFileName;

        /// <summary>
        /// CancelDeleteButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton CancelDeleteButton;

        /// <summary>
        /// ConfirmDeleteButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton ConfirmDeleteButton;

        /// <summary>
        /// ListProgress control.
        /// </summary>
        protected global::System.Web.UI.UpdateProgress ListProgress;
    }
}
