//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessor.WebForms
{
    public partial class ErrorPage
    {
        /// <summary>
        /// HeadingText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal HeadingText;

        /// <summary>
        /// MessageText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal MessageText;
    }
}
