//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentProcessor.WebForms
{
    public partial class SiteMaster
    {
        /// <summary>
        /// TitleContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;

        /// <summary>
        /// MainForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm MainForm;

        /// <summary>
        /// MainScriptManager control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager MainScriptManager;

        /// <summary>
        /// DatabasePill control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DatabasePill;

        /// <summary>
        /// DatabasePillIcon control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DatabasePillIcon;

        /// <summary>
        /// DatabasePillText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal DatabasePillText;

        /// <summary>
        /// MainContent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// CredentialSourceText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal CredentialSourceText;

        /// <summary>
        /// ProviderNameText control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ProviderNameText;
    }
}
